config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # ----Read----
  # Get all task
  get 'tasks', to: 'tasks#index' #suficiente asi
  # Get one task
  get 'tasks/new', to: 'tasks#new', as: :new_task # create

  get 'tasks/:id', to: 'tasks#show', as: :task # read
  # ----Create----
  # Show form
  post 'tasks', to: 'tasks#create'

  #----Update----
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  # ----Destroy----
  delete "tasks/:id", to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params # metodo relacionado a Active Record
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Task master</h1>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit</h2>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h2>Lista de tareas</h2>

<ol>
<% @tasks.each do |task| %>
  <li>
  <% if task.completed %>
  <i class="fas fa-check-square"></i>
<% else %>
  <i class="fas fa-square"></i>
<% end %>
  <%= link_to task.title, task_path(task.id) %></li>
<% end %>
</ol>

<h4><%= link_to "+ Agregar tarea", new_task_path %></h4>

app/views/tasks/new.html.erb
<h2>New</h2>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h2>show</h2>
<h4><% if @task.completed %>
  <i class="fas fa-check-square"></i>
<% else %>
  <i class="fas fa-square"></i>
<% end %>
<%= @task.title %></h4>
<p><%= @task.details %></p>
<br>
<h4><%= link_to "Editar tarea", edit_task_path(@task.id) %></h4>
<h4><%= link_to "Borrar tarea", delete_task_path(@task.id), method: :delete %></h4>
<p>
  <%= link_to "Go back", tasks_path %>
</p>